//! Hyprland config file generation.

use crate::hyprland::monitor::Monitor;

/// Workspace-to-monitor assignment (optional).
#[derive(Clone, Debug, Default)]
pub struct WorkspaceConfig {
    /// (workspace_id, monitor_name, default)
    pub assignments: Vec<(u32, String, bool)>,
}

/// One monitor line: name,res@hz,pos,scale
fn monitor_line(m: &Monitor) -> String {
    format!(
        "monitor={},{}@{:.2},{}x{},{}",
        m.name,
        m.resolution,
        m.refresh_rate,
        m.position.x,
        m.position.y,
        m.scale
    )
}

/// Generate Hyprland monitor config block.
pub fn generate_config(monitors: &[Monitor]) -> String {
    let mut lines = vec![
        "# Generated by hypr-monitor-tui".to_string(),
        "# https://github.com/yourusername/hypr-monitor-tui".to_string(),
        String::new(),
    ];
    for m in monitors {
        if !m.enabled {
            continue;
        }
        lines.push(monitor_line(m));
    }
    lines.join("\n")
}

/// Generate Hyprland config with workspace assignments.
pub fn generate_config_with_workspaces(
    monitors: &[Monitor],
    workspace_config: &WorkspaceConfig,
) -> String {
    let mut out = generate_config(monitors);
    if !workspace_config.assignments.is_empty() {
        out.push_str("\n\n# Workspace assignments\n");
        for (ws, mon, default) in &workspace_config.assignments {
            let def = if *default { ",default:true" } else { "" };
            out.push_str(&format!("workspace={},monitor:{}{}\n", ws, mon, def));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hyprland::monitor::{Position, Resolution, Transform};

    #[test]
    fn test_generate_config() {
        let monitors = vec![Monitor {
            name: "DP-1".to_string(),
            description: "Display".to_string(),
            position: Position { x: 0, y: 0 },
            resolution: Resolution {
                width: 2560,
                height: 1440,
            },
            available_resolutions: vec![],
            refresh_rate: 144.0,
            available_refresh_rates: vec![],
            scale: 1.0,
            transform: Transform::Normal,
            enabled: true,
            primary: true,
        }];
        let s = generate_config(&monitors);
        assert!(s.contains("monitor=DP-1"));
        assert!(s.contains("2560x1440"));
        assert!(s.contains("144.00"));
    }
}
